FROM golang:alpine AS build
WORKDIR /src
ENV CGO_ENABLED=0
COPY . .
RUN GOOS=linux GOARCH=amd64 go build -o /out/webapi_srv main.go

FROM debian

ENV DB_POSTGRES_USERNAME = "postgres"
ENV DB_POSTGRES_PASSWORD = "postgres"
ENV DB_POSTGRES_HOST_AND_PORT = "postgres:5432"
ENV DB_POSTGRES_DBNAME = "db"

EXPOSE 8080

COPY --from=build /out/webapi_srv /usr/bin/webapi_srv_workdir/webapi_srv
COPY ./bin/conf/app.conf /usr/bin/webapi_srv_workdir/conf/app.conf
COPY ./bin/swagger /usr/bin/webapi_srv_workdir/swagger

CMD /usr/bin/webapi_srv_workdir/webapi_srv