// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteUserDeleteUserIDParams creates a new DeleteUserDeleteUserIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteUserDeleteUserIDParams() *DeleteUserDeleteUserIDParams {
	return &DeleteUserDeleteUserIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteUserDeleteUserIDParamsWithTimeout creates a new DeleteUserDeleteUserIDParams object
// with the ability to set a timeout on a request.
func NewDeleteUserDeleteUserIDParamsWithTimeout(timeout time.Duration) *DeleteUserDeleteUserIDParams {
	return &DeleteUserDeleteUserIDParams{
		timeout: timeout,
	}
}

// NewDeleteUserDeleteUserIDParamsWithContext creates a new DeleteUserDeleteUserIDParams object
// with the ability to set a context for a request.
func NewDeleteUserDeleteUserIDParamsWithContext(ctx context.Context) *DeleteUserDeleteUserIDParams {
	return &DeleteUserDeleteUserIDParams{
		Context: ctx,
	}
}

// NewDeleteUserDeleteUserIDParamsWithHTTPClient creates a new DeleteUserDeleteUserIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteUserDeleteUserIDParamsWithHTTPClient(client *http.Client) *DeleteUserDeleteUserIDParams {
	return &DeleteUserDeleteUserIDParams{
		HTTPClient: client,
	}
}

/*
DeleteUserDeleteUserIDParams contains all the parameters to send to the API endpoint

	for the delete user delete user ID operation.

	Typically these are written to a http.Request.
*/
type DeleteUserDeleteUserIDParams struct {

	/* UserID.

	   Unique identifier of the user to be deleted
	*/
	UserID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete user delete user ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteUserDeleteUserIDParams) WithDefaults() *DeleteUserDeleteUserIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete user delete user ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteUserDeleteUserIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete user delete user ID params
func (o *DeleteUserDeleteUserIDParams) WithTimeout(timeout time.Duration) *DeleteUserDeleteUserIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete user delete user ID params
func (o *DeleteUserDeleteUserIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete user delete user ID params
func (o *DeleteUserDeleteUserIDParams) WithContext(ctx context.Context) *DeleteUserDeleteUserIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete user delete user ID params
func (o *DeleteUserDeleteUserIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete user delete user ID params
func (o *DeleteUserDeleteUserIDParams) WithHTTPClient(client *http.Client) *DeleteUserDeleteUserIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete user delete user ID params
func (o *DeleteUserDeleteUserIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the delete user delete user ID params
func (o *DeleteUserDeleteUserIDParams) WithUserID(userID int64) *DeleteUserDeleteUserIDParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the delete user delete user ID params
func (o *DeleteUserDeleteUserIDParams) SetUserID(userID int64) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUserDeleteUserIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param userID
	if err := r.SetPathParam("userID", swag.FormatInt64(o.UserID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
