// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMiscVersionParams creates a new GetMiscVersionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMiscVersionParams() *GetMiscVersionParams {
	return &GetMiscVersionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMiscVersionParamsWithTimeout creates a new GetMiscVersionParams object
// with the ability to set a timeout on a request.
func NewGetMiscVersionParamsWithTimeout(timeout time.Duration) *GetMiscVersionParams {
	return &GetMiscVersionParams{
		timeout: timeout,
	}
}

// NewGetMiscVersionParamsWithContext creates a new GetMiscVersionParams object
// with the ability to set a context for a request.
func NewGetMiscVersionParamsWithContext(ctx context.Context) *GetMiscVersionParams {
	return &GetMiscVersionParams{
		Context: ctx,
	}
}

// NewGetMiscVersionParamsWithHTTPClient creates a new GetMiscVersionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMiscVersionParamsWithHTTPClient(client *http.Client) *GetMiscVersionParams {
	return &GetMiscVersionParams{
		HTTPClient: client,
	}
}

/*
GetMiscVersionParams contains all the parameters to send to the API endpoint

	for the get misc version operation.

	Typically these are written to a http.Request.
*/
type GetMiscVersionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get misc version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMiscVersionParams) WithDefaults() *GetMiscVersionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get misc version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMiscVersionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get misc version params
func (o *GetMiscVersionParams) WithTimeout(timeout time.Duration) *GetMiscVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get misc version params
func (o *GetMiscVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get misc version params
func (o *GetMiscVersionParams) WithContext(ctx context.Context) *GetMiscVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get misc version params
func (o *GetMiscVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get misc version params
func (o *GetMiscVersionParams) WithHTTPClient(client *http.Client) *GetMiscVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get misc version params
func (o *GetMiscVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetMiscVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
