// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/DawnBreather/go-commons/app/poc/telemetry/client_and_tests/models"
)

// GetCarListReader is a Reader for the GetCarList structure.
type GetCarListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCarListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCarListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetCarListUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCarListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /car/list] GetCarList", response, response.Code())
	}
}

// NewGetCarListOK creates a GetCarListOK with default headers values
func NewGetCarListOK() *GetCarListOK {
	return &GetCarListOK{}
}

/*
GetCarListOK describes a response with status code 200, with default header values.

An array of cars
*/
type GetCarListOK struct {
	Payload []*models.Car
}

// IsSuccess returns true when this get car list o k response has a 2xx status code
func (o *GetCarListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get car list o k response has a 3xx status code
func (o *GetCarListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get car list o k response has a 4xx status code
func (o *GetCarListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get car list o k response has a 5xx status code
func (o *GetCarListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get car list o k response a status code equal to that given
func (o *GetCarListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get car list o k response
func (o *GetCarListOK) Code() int {
	return 200
}

func (o *GetCarListOK) Error() string {
	return fmt.Sprintf("[GET /car/list][%d] getCarListOK  %+v", 200, o.Payload)
}

func (o *GetCarListOK) String() string {
	return fmt.Sprintf("[GET /car/list][%d] getCarListOK  %+v", 200, o.Payload)
}

func (o *GetCarListOK) GetPayload() []*models.Car {
	return o.Payload
}

func (o *GetCarListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCarListUnauthorized creates a GetCarListUnauthorized with default headers values
func NewGetCarListUnauthorized() *GetCarListUnauthorized {
	return &GetCarListUnauthorized{}
}

/*
GetCarListUnauthorized describes a response with status code 401, with default header values.

Unauthorized attempt to list cars
*/
type GetCarListUnauthorized struct {
	Payload *GetCarListUnauthorizedBody
}

// IsSuccess returns true when this get car list unauthorized response has a 2xx status code
func (o *GetCarListUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get car list unauthorized response has a 3xx status code
func (o *GetCarListUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get car list unauthorized response has a 4xx status code
func (o *GetCarListUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get car list unauthorized response has a 5xx status code
func (o *GetCarListUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get car list unauthorized response a status code equal to that given
func (o *GetCarListUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get car list unauthorized response
func (o *GetCarListUnauthorized) Code() int {
	return 401
}

func (o *GetCarListUnauthorized) Error() string {
	return fmt.Sprintf("[GET /car/list][%d] getCarListUnauthorized  %+v", 401, o.Payload)
}

func (o *GetCarListUnauthorized) String() string {
	return fmt.Sprintf("[GET /car/list][%d] getCarListUnauthorized  %+v", 401, o.Payload)
}

func (o *GetCarListUnauthorized) GetPayload() *GetCarListUnauthorizedBody {
	return o.Payload
}

func (o *GetCarListUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetCarListUnauthorizedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCarListInternalServerError creates a GetCarListInternalServerError with default headers values
func NewGetCarListInternalServerError() *GetCarListInternalServerError {
	return &GetCarListInternalServerError{}
}

/*
GetCarListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error or error retrieving cars
*/
type GetCarListInternalServerError struct {
	Payload *GetCarListInternalServerErrorBody
}

// IsSuccess returns true when this get car list internal server error response has a 2xx status code
func (o *GetCarListInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get car list internal server error response has a 3xx status code
func (o *GetCarListInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get car list internal server error response has a 4xx status code
func (o *GetCarListInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get car list internal server error response has a 5xx status code
func (o *GetCarListInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get car list internal server error response a status code equal to that given
func (o *GetCarListInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get car list internal server error response
func (o *GetCarListInternalServerError) Code() int {
	return 500
}

func (o *GetCarListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /car/list][%d] getCarListInternalServerError  %+v", 500, o.Payload)
}

func (o *GetCarListInternalServerError) String() string {
	return fmt.Sprintf("[GET /car/list][%d] getCarListInternalServerError  %+v", 500, o.Payload)
}

func (o *GetCarListInternalServerError) GetPayload() *GetCarListInternalServerErrorBody {
	return o.Payload
}

func (o *GetCarListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetCarListInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetCarListInternalServerErrorBody get car list internal server error body
swagger:model GetCarListInternalServerErrorBody
*/
type GetCarListInternalServerErrorBody struct {

	// error
	// Example: Error retrieving cars
	Error string `json:"error,omitempty"`
}

// Validate validates this get car list internal server error body
func (o *GetCarListInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get car list internal server error body based on context it is used
func (o *GetCarListInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCarListInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCarListInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res GetCarListInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
GetCarListUnauthorizedBody get car list unauthorized body
swagger:model GetCarListUnauthorizedBody
*/
type GetCarListUnauthorizedBody struct {

	// error
	// Example: Unauthorized
	Error string `json:"error,omitempty"`
}

// Validate validates this get car list unauthorized body
func (o *GetCarListUnauthorizedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get car list unauthorized body based on context it is used
func (o *GetCarListUnauthorizedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCarListUnauthorizedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCarListUnauthorizedBody) UnmarshalBinary(b []byte) error {
	var res GetCarListUnauthorizedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
