// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCarListParams creates a new GetCarListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCarListParams() *GetCarListParams {
	return &GetCarListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCarListParamsWithTimeout creates a new GetCarListParams object
// with the ability to set a timeout on a request.
func NewGetCarListParamsWithTimeout(timeout time.Duration) *GetCarListParams {
	return &GetCarListParams{
		timeout: timeout,
	}
}

// NewGetCarListParamsWithContext creates a new GetCarListParams object
// with the ability to set a context for a request.
func NewGetCarListParamsWithContext(ctx context.Context) *GetCarListParams {
	return &GetCarListParams{
		Context: ctx,
	}
}

// NewGetCarListParamsWithHTTPClient creates a new GetCarListParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCarListParamsWithHTTPClient(client *http.Client) *GetCarListParams {
	return &GetCarListParams{
		HTTPClient: client,
	}
}

/*
GetCarListParams contains all the parameters to send to the API endpoint

	for the get car list operation.

	Typically these are written to a http.Request.
*/
type GetCarListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get car list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCarListParams) WithDefaults() *GetCarListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get car list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCarListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get car list params
func (o *GetCarListParams) WithTimeout(timeout time.Duration) *GetCarListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get car list params
func (o *GetCarListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get car list params
func (o *GetCarListParams) WithContext(ctx context.Context) *GetCarListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get car list params
func (o *GetCarListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get car list params
func (o *GetCarListParams) WithHTTPClient(client *http.Client) *GetCarListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get car list params
func (o *GetCarListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCarListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
