// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/DawnBreather/go-commons/app/poc/telemetry/client_and_tests/models"
)

// GetUserListReader is a Reader for the GetUserList structure.
type GetUserListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUserListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetUserListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /user/list] GetUserList", response, response.Code())
	}
}

// NewGetUserListOK creates a GetUserListOK with default headers values
func NewGetUserListOK() *GetUserListOK {
	return &GetUserListOK{}
}

/*
GetUserListOK describes a response with status code 200, with default header values.

An array of users
*/
type GetUserListOK struct {
	Payload []*models.User
}

// IsSuccess returns true when this get user list o k response has a 2xx status code
func (o *GetUserListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get user list o k response has a 3xx status code
func (o *GetUserListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get user list o k response has a 4xx status code
func (o *GetUserListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get user list o k response has a 5xx status code
func (o *GetUserListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get user list o k response a status code equal to that given
func (o *GetUserListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get user list o k response
func (o *GetUserListOK) Code() int {
	return 200
}

func (o *GetUserListOK) Error() string {
	return fmt.Sprintf("[GET /user/list][%d] getUserListOK  %+v", 200, o.Payload)
}

func (o *GetUserListOK) String() string {
	return fmt.Sprintf("[GET /user/list][%d] getUserListOK  %+v", 200, o.Payload)
}

func (o *GetUserListOK) GetPayload() []*models.User {
	return o.Payload
}

func (o *GetUserListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUserListInternalServerError creates a GetUserListInternalServerError with default headers values
func NewGetUserListInternalServerError() *GetUserListInternalServerError {
	return &GetUserListInternalServerError{}
}

/*
GetUserListInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetUserListInternalServerError struct {
	Payload *GetUserListInternalServerErrorBody
}

// IsSuccess returns true when this get user list internal server error response has a 2xx status code
func (o *GetUserListInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get user list internal server error response has a 3xx status code
func (o *GetUserListInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get user list internal server error response has a 4xx status code
func (o *GetUserListInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get user list internal server error response has a 5xx status code
func (o *GetUserListInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get user list internal server error response a status code equal to that given
func (o *GetUserListInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get user list internal server error response
func (o *GetUserListInternalServerError) Code() int {
	return 500
}

func (o *GetUserListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /user/list][%d] getUserListInternalServerError  %+v", 500, o.Payload)
}

func (o *GetUserListInternalServerError) String() string {
	return fmt.Sprintf("[GET /user/list][%d] getUserListInternalServerError  %+v", 500, o.Payload)
}

func (o *GetUserListInternalServerError) GetPayload() *GetUserListInternalServerErrorBody {
	return o.Payload
}

func (o *GetUserListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetUserListInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetUserListInternalServerErrorBody get user list internal server error body
swagger:model GetUserListInternalServerErrorBody
*/
type GetUserListInternalServerErrorBody struct {

	// error
	// Example: Error retrieving users
	Error string `json:"error,omitempty"`
}

// Validate validates this get user list internal server error body
func (o *GetUserListInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get user list internal server error body based on context it is used
func (o *GetUserListInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetUserListInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetUserListInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res GetUserListInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
