// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/DawnBreather/go-commons/app/poc/telemetry/client_and_tests/models"
)

// GetMiscVersionReader is a Reader for the GetMiscVersion structure.
type GetMiscVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMiscVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMiscVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /misc/version] GetMiscVersion", response, response.Code())
	}
}

// NewGetMiscVersionOK creates a GetMiscVersionOK with default headers values
func NewGetMiscVersionOK() *GetMiscVersionOK {
	return &GetMiscVersionOK{}
}

/*
GetMiscVersionOK describes a response with status code 200, with default header values.

API version information
*/
type GetMiscVersionOK struct {
	Payload *models.VersionResponse
}

// IsSuccess returns true when this get misc version o k response has a 2xx status code
func (o *GetMiscVersionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get misc version o k response has a 3xx status code
func (o *GetMiscVersionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get misc version o k response has a 4xx status code
func (o *GetMiscVersionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get misc version o k response has a 5xx status code
func (o *GetMiscVersionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get misc version o k response a status code equal to that given
func (o *GetMiscVersionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get misc version o k response
func (o *GetMiscVersionOK) Code() int {
	return 200
}

func (o *GetMiscVersionOK) Error() string {
	return fmt.Sprintf("[GET /misc/version][%d] getMiscVersionOK  %+v", 200, o.Payload)
}

func (o *GetMiscVersionOK) String() string {
	return fmt.Sprintf("[GET /misc/version][%d] getMiscVersionOK  %+v", 200, o.Payload)
}

func (o *GetMiscVersionOK) GetPayload() *models.VersionResponse {
	return o.Payload
}

func (o *GetMiscVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VersionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
