// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetCarCarIDParams creates a new GetCarCarIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCarCarIDParams() *GetCarCarIDParams {
	return &GetCarCarIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCarCarIDParamsWithTimeout creates a new GetCarCarIDParams object
// with the ability to set a timeout on a request.
func NewGetCarCarIDParamsWithTimeout(timeout time.Duration) *GetCarCarIDParams {
	return &GetCarCarIDParams{
		timeout: timeout,
	}
}

// NewGetCarCarIDParamsWithContext creates a new GetCarCarIDParams object
// with the ability to set a context for a request.
func NewGetCarCarIDParamsWithContext(ctx context.Context) *GetCarCarIDParams {
	return &GetCarCarIDParams{
		Context: ctx,
	}
}

// NewGetCarCarIDParamsWithHTTPClient creates a new GetCarCarIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCarCarIDParamsWithHTTPClient(client *http.Client) *GetCarCarIDParams {
	return &GetCarCarIDParams{
		HTTPClient: client,
	}
}

/*
GetCarCarIDParams contains all the parameters to send to the API endpoint

	for the get car car ID operation.

	Typically these are written to a http.Request.
*/
type GetCarCarIDParams struct {

	/* CarID.

	   Unique identifier of the car
	*/
	CarID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get car car ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCarCarIDParams) WithDefaults() *GetCarCarIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get car car ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCarCarIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get car car ID params
func (o *GetCarCarIDParams) WithTimeout(timeout time.Duration) *GetCarCarIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get car car ID params
func (o *GetCarCarIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get car car ID params
func (o *GetCarCarIDParams) WithContext(ctx context.Context) *GetCarCarIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get car car ID params
func (o *GetCarCarIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get car car ID params
func (o *GetCarCarIDParams) WithHTTPClient(client *http.Client) *GetCarCarIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get car car ID params
func (o *GetCarCarIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCarID adds the carID to the get car car ID params
func (o *GetCarCarIDParams) WithCarID(carID int64) *GetCarCarIDParams {
	o.SetCarID(carID)
	return o
}

// SetCarID adds the carId to the get car car ID params
func (o *GetCarCarIDParams) SetCarID(carID int64) {
	o.CarID = carID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCarCarIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param carID
	if err := r.SetPathParam("carID", swag.FormatInt64(o.CarID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
