// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/DawnBreather/go-commons/app/poc/telemetry/client_and_tests/models"
)

// GetMiscHealthReader is a Reader for the GetMiscHealth structure.
type GetMiscHealthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMiscHealthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMiscHealthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /misc/health] GetMiscHealth", response, response.Code())
	}
}

// NewGetMiscHealthOK creates a GetMiscHealthOK with default headers values
func NewGetMiscHealthOK() *GetMiscHealthOK {
	return &GetMiscHealthOK{}
}

/*
GetMiscHealthOK describes a response with status code 200, with default header values.

API is healthy
*/
type GetMiscHealthOK struct {
	Payload *models.HealthResponse
}

// IsSuccess returns true when this get misc health o k response has a 2xx status code
func (o *GetMiscHealthOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get misc health o k response has a 3xx status code
func (o *GetMiscHealthOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get misc health o k response has a 4xx status code
func (o *GetMiscHealthOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get misc health o k response has a 5xx status code
func (o *GetMiscHealthOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get misc health o k response a status code equal to that given
func (o *GetMiscHealthOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get misc health o k response
func (o *GetMiscHealthOK) Code() int {
	return 200
}

func (o *GetMiscHealthOK) Error() string {
	return fmt.Sprintf("[GET /misc/health][%d] getMiscHealthOK  %+v", 200, o.Payload)
}

func (o *GetMiscHealthOK) String() string {
	return fmt.Sprintf("[GET /misc/health][%d] getMiscHealthOK  %+v", 200, o.Payload)
}

func (o *GetMiscHealthOK) GetPayload() *models.HealthResponse {
	return o.Payload
}

func (o *GetMiscHealthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HealthResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
