// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/DawnBreather/go-commons/app/poc/telemetry/client_and_tests/models"
)

// NewPostCarCreateParams creates a new PostCarCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostCarCreateParams() *PostCarCreateParams {
	return &PostCarCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostCarCreateParamsWithTimeout creates a new PostCarCreateParams object
// with the ability to set a timeout on a request.
func NewPostCarCreateParamsWithTimeout(timeout time.Duration) *PostCarCreateParams {
	return &PostCarCreateParams{
		timeout: timeout,
	}
}

// NewPostCarCreateParamsWithContext creates a new PostCarCreateParams object
// with the ability to set a context for a request.
func NewPostCarCreateParamsWithContext(ctx context.Context) *PostCarCreateParams {
	return &PostCarCreateParams{
		Context: ctx,
	}
}

// NewPostCarCreateParamsWithHTTPClient creates a new PostCarCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostCarCreateParamsWithHTTPClient(client *http.Client) *PostCarCreateParams {
	return &PostCarCreateParams{
		HTTPClient: client,
	}
}

/*
PostCarCreateParams contains all the parameters to send to the API endpoint

	for the post car create operation.

	Typically these are written to a http.Request.
*/
type PostCarCreateParams struct {

	/* Body.

	   Car object that needs to be added to the system
	*/
	Body *models.Car

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post car create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCarCreateParams) WithDefaults() *PostCarCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post car create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCarCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post car create params
func (o *PostCarCreateParams) WithTimeout(timeout time.Duration) *PostCarCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post car create params
func (o *PostCarCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post car create params
func (o *PostCarCreateParams) WithContext(ctx context.Context) *PostCarCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post car create params
func (o *PostCarCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post car create params
func (o *PostCarCreateParams) WithHTTPClient(client *http.Client) *PostCarCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post car create params
func (o *PostCarCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post car create params
func (o *PostCarCreateParams) WithBody(body *models.Car) *PostCarCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post car create params
func (o *PostCarCreateParams) SetBody(body *models.Car) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostCarCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
