// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/DawnBreather/go-commons/app/poc/telemetry/client_and_tests/models"
)

// NewPostUserCreateParams creates a new PostUserCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostUserCreateParams() *PostUserCreateParams {
	return &PostUserCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostUserCreateParamsWithTimeout creates a new PostUserCreateParams object
// with the ability to set a timeout on a request.
func NewPostUserCreateParamsWithTimeout(timeout time.Duration) *PostUserCreateParams {
	return &PostUserCreateParams{
		timeout: timeout,
	}
}

// NewPostUserCreateParamsWithContext creates a new PostUserCreateParams object
// with the ability to set a context for a request.
func NewPostUserCreateParamsWithContext(ctx context.Context) *PostUserCreateParams {
	return &PostUserCreateParams{
		Context: ctx,
	}
}

// NewPostUserCreateParamsWithHTTPClient creates a new PostUserCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostUserCreateParamsWithHTTPClient(client *http.Client) *PostUserCreateParams {
	return &PostUserCreateParams{
		HTTPClient: client,
	}
}

/*
PostUserCreateParams contains all the parameters to send to the API endpoint

	for the post user create operation.

	Typically these are written to a http.Request.
*/
type PostUserCreateParams struct {

	/* Body.

	   User object that needs to be added to the system
	*/
	Body *models.User

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post user create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostUserCreateParams) WithDefaults() *PostUserCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post user create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostUserCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post user create params
func (o *PostUserCreateParams) WithTimeout(timeout time.Duration) *PostUserCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post user create params
func (o *PostUserCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post user create params
func (o *PostUserCreateParams) WithContext(ctx context.Context) *PostUserCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post user create params
func (o *PostUserCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post user create params
func (o *PostUserCreateParams) WithHTTPClient(client *http.Client) *PostUserCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post user create params
func (o *PostUserCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post user create params
func (o *PostUserCreateParams) WithBody(body *models.User) *PostUserCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post user create params
func (o *PostUserCreateParams) SetBody(body *models.User) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostUserCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
