// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostCarCreateReader is a Reader for the PostCarCreate structure.
type PostCarCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCarCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostCarCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostCarCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostCarCreateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostCarCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /car/create] PostCarCreate", response, response.Code())
	}
}

// NewPostCarCreateOK creates a PostCarCreateOK with default headers values
func NewPostCarCreateOK() *PostCarCreateOK {
	return &PostCarCreateOK{}
}

/*
PostCarCreateOK describes a response with status code 200, with default header values.

Car created successfully
*/
type PostCarCreateOK struct {
	Payload *PostCarCreateOKBody
}

// IsSuccess returns true when this post car create o k response has a 2xx status code
func (o *PostCarCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post car create o k response has a 3xx status code
func (o *PostCarCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post car create o k response has a 4xx status code
func (o *PostCarCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post car create o k response has a 5xx status code
func (o *PostCarCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post car create o k response a status code equal to that given
func (o *PostCarCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post car create o k response
func (o *PostCarCreateOK) Code() int {
	return 200
}

func (o *PostCarCreateOK) Error() string {
	return fmt.Sprintf("[POST /car/create][%d] postCarCreateOK  %+v", 200, o.Payload)
}

func (o *PostCarCreateOK) String() string {
	return fmt.Sprintf("[POST /car/create][%d] postCarCreateOK  %+v", 200, o.Payload)
}

func (o *PostCarCreateOK) GetPayload() *PostCarCreateOKBody {
	return o.Payload
}

func (o *PostCarCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostCarCreateOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostCarCreateBadRequest creates a PostCarCreateBadRequest with default headers values
func NewPostCarCreateBadRequest() *PostCarCreateBadRequest {
	return &PostCarCreateBadRequest{}
}

/*
PostCarCreateBadRequest describes a response with status code 400, with default header values.

Bad request or error parsing request data
*/
type PostCarCreateBadRequest struct {
}

// IsSuccess returns true when this post car create bad request response has a 2xx status code
func (o *PostCarCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post car create bad request response has a 3xx status code
func (o *PostCarCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post car create bad request response has a 4xx status code
func (o *PostCarCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post car create bad request response has a 5xx status code
func (o *PostCarCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post car create bad request response a status code equal to that given
func (o *PostCarCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post car create bad request response
func (o *PostCarCreateBadRequest) Code() int {
	return 400
}

func (o *PostCarCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /car/create][%d] postCarCreateBadRequest ", 400)
}

func (o *PostCarCreateBadRequest) String() string {
	return fmt.Sprintf("[POST /car/create][%d] postCarCreateBadRequest ", 400)
}

func (o *PostCarCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCarCreateUnauthorized creates a PostCarCreateUnauthorized with default headers values
func NewPostCarCreateUnauthorized() *PostCarCreateUnauthorized {
	return &PostCarCreateUnauthorized{}
}

/*
PostCarCreateUnauthorized describes a response with status code 401, with default header values.

Unauthorized attempt to create car
*/
type PostCarCreateUnauthorized struct {
}

// IsSuccess returns true when this post car create unauthorized response has a 2xx status code
func (o *PostCarCreateUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post car create unauthorized response has a 3xx status code
func (o *PostCarCreateUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post car create unauthorized response has a 4xx status code
func (o *PostCarCreateUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post car create unauthorized response has a 5xx status code
func (o *PostCarCreateUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post car create unauthorized response a status code equal to that given
func (o *PostCarCreateUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post car create unauthorized response
func (o *PostCarCreateUnauthorized) Code() int {
	return 401
}

func (o *PostCarCreateUnauthorized) Error() string {
	return fmt.Sprintf("[POST /car/create][%d] postCarCreateUnauthorized ", 401)
}

func (o *PostCarCreateUnauthorized) String() string {
	return fmt.Sprintf("[POST /car/create][%d] postCarCreateUnauthorized ", 401)
}

func (o *PostCarCreateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostCarCreateInternalServerError creates a PostCarCreateInternalServerError with default headers values
func NewPostCarCreateInternalServerError() *PostCarCreateInternalServerError {
	return &PostCarCreateInternalServerError{}
}

/*
PostCarCreateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error or error creating car
*/
type PostCarCreateInternalServerError struct {
}

// IsSuccess returns true when this post car create internal server error response has a 2xx status code
func (o *PostCarCreateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post car create internal server error response has a 3xx status code
func (o *PostCarCreateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post car create internal server error response has a 4xx status code
func (o *PostCarCreateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post car create internal server error response has a 5xx status code
func (o *PostCarCreateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post car create internal server error response a status code equal to that given
func (o *PostCarCreateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post car create internal server error response
func (o *PostCarCreateInternalServerError) Code() int {
	return 500
}

func (o *PostCarCreateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /car/create][%d] postCarCreateInternalServerError ", 500)
}

func (o *PostCarCreateInternalServerError) String() string {
	return fmt.Sprintf("[POST /car/create][%d] postCarCreateInternalServerError ", 500)
}

func (o *PostCarCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
PostCarCreateOKBody post car create o k body
swagger:model PostCarCreateOKBody
*/
type PostCarCreateOKBody struct {

	// result
	// Example: success
	Result string `json:"result,omitempty"`
}

// Validate validates this post car create o k body
func (o *PostCarCreateOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post car create o k body based on context it is used
func (o *PostCarCreateOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostCarCreateOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostCarCreateOKBody) UnmarshalBinary(b []byte) error {
	var res PostCarCreateOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
