// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/DawnBreather/go-commons/app/poc/telemetry/client_and_tests/models"
)

// PostUserCreateReader is a Reader for the PostUserCreate structure.
type PostUserCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostUserCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostUserCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostUserCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostUserCreateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /user/create] PostUserCreate", response, response.Code())
	}
}

// NewPostUserCreateOK creates a PostUserCreateOK with default headers values
func NewPostUserCreateOK() *PostUserCreateOK {
	return &PostUserCreateOK{}
}

/*
PostUserCreateOK describes a response with status code 200, with default header values.

User created successfully
*/
type PostUserCreateOK struct {
	Payload *models.StandardResponse
}

// IsSuccess returns true when this post user create o k response has a 2xx status code
func (o *PostUserCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post user create o k response has a 3xx status code
func (o *PostUserCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post user create o k response has a 4xx status code
func (o *PostUserCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post user create o k response has a 5xx status code
func (o *PostUserCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post user create o k response a status code equal to that given
func (o *PostUserCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post user create o k response
func (o *PostUserCreateOK) Code() int {
	return 200
}

func (o *PostUserCreateOK) Error() string {
	return fmt.Sprintf("[POST /user/create][%d] postUserCreateOK  %+v", 200, o.Payload)
}

func (o *PostUserCreateOK) String() string {
	return fmt.Sprintf("[POST /user/create][%d] postUserCreateOK  %+v", 200, o.Payload)
}

func (o *PostUserCreateOK) GetPayload() *models.StandardResponse {
	return o.Payload
}

func (o *PostUserCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StandardResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostUserCreateBadRequest creates a PostUserCreateBadRequest with default headers values
func NewPostUserCreateBadRequest() *PostUserCreateBadRequest {
	return &PostUserCreateBadRequest{}
}

/*
PostUserCreateBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type PostUserCreateBadRequest struct {
}

// IsSuccess returns true when this post user create bad request response has a 2xx status code
func (o *PostUserCreateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post user create bad request response has a 3xx status code
func (o *PostUserCreateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post user create bad request response has a 4xx status code
func (o *PostUserCreateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post user create bad request response has a 5xx status code
func (o *PostUserCreateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post user create bad request response a status code equal to that given
func (o *PostUserCreateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post user create bad request response
func (o *PostUserCreateBadRequest) Code() int {
	return 400
}

func (o *PostUserCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /user/create][%d] postUserCreateBadRequest ", 400)
}

func (o *PostUserCreateBadRequest) String() string {
	return fmt.Sprintf("[POST /user/create][%d] postUserCreateBadRequest ", 400)
}

func (o *PostUserCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostUserCreateInternalServerError creates a PostUserCreateInternalServerError with default headers values
func NewPostUserCreateInternalServerError() *PostUserCreateInternalServerError {
	return &PostUserCreateInternalServerError{}
}

/*
PostUserCreateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostUserCreateInternalServerError struct {
}

// IsSuccess returns true when this post user create internal server error response has a 2xx status code
func (o *PostUserCreateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post user create internal server error response has a 3xx status code
func (o *PostUserCreateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post user create internal server error response has a 4xx status code
func (o *PostUserCreateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post user create internal server error response has a 5xx status code
func (o *PostUserCreateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post user create internal server error response a status code equal to that given
func (o *PostUserCreateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post user create internal server error response
func (o *PostUserCreateInternalServerError) Code() int {
	return 500
}

func (o *PostUserCreateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /user/create][%d] postUserCreateInternalServerError ", 500)
}

func (o *PostUserCreateInternalServerError) String() string {
	return fmt.Sprintf("[POST /user/create][%d] postUserCreateInternalServerError ", 500)
}

func (o *PostUserCreateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
