// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/DawnBreather/go-commons/app/poc/telemetry/client_and_tests/models"
)

// NewPutCarUpdateCarIDParams creates a new PutCarUpdateCarIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutCarUpdateCarIDParams() *PutCarUpdateCarIDParams {
	return &PutCarUpdateCarIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutCarUpdateCarIDParamsWithTimeout creates a new PutCarUpdateCarIDParams object
// with the ability to set a timeout on a request.
func NewPutCarUpdateCarIDParamsWithTimeout(timeout time.Duration) *PutCarUpdateCarIDParams {
	return &PutCarUpdateCarIDParams{
		timeout: timeout,
	}
}

// NewPutCarUpdateCarIDParamsWithContext creates a new PutCarUpdateCarIDParams object
// with the ability to set a context for a request.
func NewPutCarUpdateCarIDParamsWithContext(ctx context.Context) *PutCarUpdateCarIDParams {
	return &PutCarUpdateCarIDParams{
		Context: ctx,
	}
}

// NewPutCarUpdateCarIDParamsWithHTTPClient creates a new PutCarUpdateCarIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutCarUpdateCarIDParamsWithHTTPClient(client *http.Client) *PutCarUpdateCarIDParams {
	return &PutCarUpdateCarIDParams{
		HTTPClient: client,
	}
}

/*
PutCarUpdateCarIDParams contains all the parameters to send to the API endpoint

	for the put car update car ID operation.

	Typically these are written to a http.Request.
*/
type PutCarUpdateCarIDParams struct {

	/* Body.

	   Car object with updated information
	*/
	Body *models.Car

	/* CarID.

	   Unique identifier of the car
	*/
	CarID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put car update car ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutCarUpdateCarIDParams) WithDefaults() *PutCarUpdateCarIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put car update car ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutCarUpdateCarIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put car update car ID params
func (o *PutCarUpdateCarIDParams) WithTimeout(timeout time.Duration) *PutCarUpdateCarIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put car update car ID params
func (o *PutCarUpdateCarIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put car update car ID params
func (o *PutCarUpdateCarIDParams) WithContext(ctx context.Context) *PutCarUpdateCarIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put car update car ID params
func (o *PutCarUpdateCarIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put car update car ID params
func (o *PutCarUpdateCarIDParams) WithHTTPClient(client *http.Client) *PutCarUpdateCarIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put car update car ID params
func (o *PutCarUpdateCarIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put car update car ID params
func (o *PutCarUpdateCarIDParams) WithBody(body *models.Car) *PutCarUpdateCarIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put car update car ID params
func (o *PutCarUpdateCarIDParams) SetBody(body *models.Car) {
	o.Body = body
}

// WithCarID adds the carID to the put car update car ID params
func (o *PutCarUpdateCarIDParams) WithCarID(carID int64) *PutCarUpdateCarIDParams {
	o.SetCarID(carID)
	return o
}

// SetCarID adds the carId to the put car update car ID params
func (o *PutCarUpdateCarIDParams) SetCarID(carID int64) {
	o.CarID = carID
}

// WriteToRequest writes these params to a swagger request
func (o *PutCarUpdateCarIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param carID
	if err := r.SetPathParam("carID", swag.FormatInt64(o.CarID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
